version: "3.9"
   
services:
  db:
    image: postgres:9.5 # 9.5 supported by Django 3.2.X (LTS)
    container_name: site_db
    volumes:
      - ./data/db:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=${POSTGRES_DB:?missing db POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER:?missing db POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:?missing db POSTGRES_USER}
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 5s
      timeout: 4s
      retries: 5
  web:
    build: .
    container_name: site_web
    command: python manage.py runserver 0.0.0.0:${WEB_PORT:?missing WEB_PORT}
    volumes:
      - .:${CODE_DIRECTORY:?missing code folder}
    ports:
      - "${WEB_PORT:?missing WEB_PORT}:${WEB_PORT:?missing WEB_PORT}"
    environment:
      - POSTGRES_DB=${POSTGRES_DB:?missing web POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER:?missing web POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:?missing web POSTGRES_PASSWORD}
    depends_on:
      db:
        condition: service_healthy