version: "3.9"
   
services:
  db:
    image: postgres
    volumes:
      - ./data/db:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=${POSTGRES_DB:?missing db POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER:?missing db POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:?missing db POSTGRES_USER}
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:${WEB_PORT:?missing WEB_PORT}
    volumes:
      - .:${CODE_DIRECTORY:?missing code folder}
    ports:
      - "${WEB_PORT:?missing WEB_PORT}:${WEB_PORT:?missing WEB_PORT}"
    environment:
      - POSTGRES_DB=${POSTGRES_DB:?missing web POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER:?missing web POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:?missing web POSTGRES_PASSWORD}
    depends_on:
      - db